service: crypto-binance-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: prod
  environment: ${file(env.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "secretsmanager:*"

functions:
  # API V1
  ## Trade
  V1APITrade:
    handler: src/app/v1/trade/index.trade
    events:
      - http:
          path: /api/v1/trade
          method: post
          cors: true
          private: false
  V1APIGetBalance:
    handler: src/app/v1/trade/index.getBalance
    events:
      - http:
          path: /api/v1/balance
          method: get
          cors: true
          private: false
